pipeline {
   agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package -Dhttps.proxyHost=10.0.0.22 -Dhttps.proxyPort=8118'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test -Dhttps.proxyHost=10.0.0.22 -Dhttps.proxyPort=8118'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
